feat(dump-fzf): unified dumping root + logging

diff --git a/dump-fzf b/dump-fzf
--- a/dump-fzf
+++ b/dump-fzf
@@ -16,8 +16,15 @@ EOM
 
 # }}} CREDENTIALS
 
+DUMPS_ROOT="${HOME}/db_dumps"
+[[ ! -d $DUMPS_ROOT ]] \
+    && echo "[INFO] creating $DUMPS_ROOT" \
+    && mkdir -p "$DUMPS_ROOT"
+
+# }}} CREDENTIALS
+
 choice=$(echo ${!projects[@]} | tr ' ' '\n' | fzf)
-[ -z $choice ] && echo "nothing chosen...exiting" && exit 1
+[ -z $choice ] && echo "[ERROR] nothing chosen...exiting" && exit 1
 
 lines="${projects[$choice]}"
 
@@ -30,6 +37,7 @@ pass=$(echo "$lines" | sed -n '5p')
 bridge_port="3333"
 socket_file="/tmp/db-backup-socket"
 
+echo "[INFO] creating ssh tunnel..."
 ssh -L \
     "${bridge_port}:127.0.0.1:${port}" \
     -M \
@@ -38,16 +46,22 @@ ssh -L \
 
 stamp=$(date "+%Y.%m.%d-%H.%M.%S")
 
+DUMP_LOCATION="${DUMPS_ROOT}/${choice}"
+[[ ! -d $DUMP_LOCATION ]] \
+    && echo "creating $DUMP_LOCATION" \
+    && mkdir "$DUMP_LOCATION"
+
+echo "[INFO] dumping database..."
 export PGPASSWORD="$pass"
 pg_dump \
     -p "$bridge_port" \
     -h localhost \
     -U "$user" \
     -d "$db" \
-    --file="${HOME}/${db}-${stamp}.sql" \
+    --file="${DUMP_LOCATION}/${stamp}.sql" \
     --column-inserts
 
+echo "[INFO] removing ssh tunnel..."
 ssh \
     -S "$socket_file" \
     -O exit "$location"
-
