feat(transfer_model_to_sd): macos rewrite

diff --git a/transfer_model_to_sd b/transfer_model_to_sd
--- a/transfer_model_to_sd
+++ b/transfer_model_to_sd
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-ROOT=~/Documents/gcodes
-PARTITION=/dev/sda1
-MOUNTPOINT=/mnt
+ROOT=~/3d/gcodes
+DESTINATION="/Volumes/NO NAME"
 
 keep_files=(
     "frame_calibration.gcode"
@@ -14,16 +13,15 @@ keep_files=(
 SEPARATOR="#################################"
 
 # select files to copy
-chosen=$(ls -t $ROOT | rofi -dmenu -i -p -multi-select 'Choose gcode')
-[[ -z $chosen ]] \
+choice=$(ls -t $ROOT | fzf -e -m)
+[[ ! $? -eq 0 ]] \
     && echo "[INFO] nothing chosen exiting..." \
     && exit 0
 
 # check if sd present, then mount
-[ ! -b $PARTITION ] \
-    && echo "[ERROR] No $PARTITION plugged in" \
+[ ! -d "$DESTINATION" ] \
+    && echo "[ERROR] Plug in sd card!" \
     && exit 0
-sudo mount $PARTITION $MOUNTPOINT
 
 if [[ $1 == "-r" ]]; then # remove all previous files
     # prepare flags to exclude these files from removing
@@ -36,7 +34,7 @@ if [[ $1 == "-r" ]]; then # remove all previous files
     echo $SEPARATOR
 
     # remove whats not to keep
-    sudo find $MOUNTPOINT \
+    sudo find "$DESTINATION" \
         -name "*.gcode" \
         -and $not_find_flags \
         -exec echo "[INFO] removing" {} \; \
@@ -48,10 +46,7 @@ echo "[INFO] transferring:"
 while read -r chosen_file; do
     echo "    $chosen_file"
     full_path="$ROOT/$chosen_file"
-    sudo cp $full_path $MOUNTPOINT
-done <<< "$chosen"
-
-# unmount
-sudo umount $PARTITION
+    sudo cp "$full_path" "$DESTINATION"
+done <<< "$choice"
 
 echo "[INFO] Done"
